#!/bin/sh

PANEL_FIFO=/tmp/bar.fifo

[ -e $PANEL_FIFO ] && rm $PANEL_FIFO
mkfifo $PANEL_FIFO

# Run bar
cat $PANEL_FIFO | ./printer.coffee &

# Display time
~/Github/baskerville/sutils/clock -s -i 10 -f 'S%d %b - %I:%M %p' > $PANEL_FIFO &

# Timer
# while true
# do

#   # Display volume
#   osascript -e "\"V\" & output volume of (get volume settings)" > $PANEL_FIFO

#   sleep 1
# done

